apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - k8s-cart-deployment.yaml
  - k8s-database-deployment.yaml
  - k8s-deployment.yaml
  - k8s-order-deployment.yaml
  - k8s-users-deployment.yaml
  - gateway.yaml