apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
patches:
- target:
    group: field.vmware.com
    version: v1
    kind: ArgoCluster
  patch: |-
    - op: replace
      path: /spec/clusterLabels/type
      value: tenant