apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../../../../apps/base/istio-ako-patch
components:
- ../../../../../apps/components/stacks/standard
- ../../../../../apps/components/stacks/service-mesh
- ../../../../../apps/components/stacks/observability
- ../../../../../apps/components/envs/dev

