apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
resources:
- ../../base/antrea-config
patches:
- target:
    group: cni.tanzu.vmware.com
    version: v1alpha1
    kind: AntreaConfig
    name: clustername-antrea-package
  patch: |-
    - op: replace
      path: /spec/antreaNSX/enable
      value: true
# configMapGenerator:
#   - name: vars
#     literals:
#       - cluster_name=chnageme
# generatorOptions:
#   disableNameSuffixHash: true
#   annotations:
#     config.kubernetes.io/local-config: "true"