apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
resources:
- ../../base/antrea-config
patches:
- target:
    group: cni.tanzu.vmware.com
    version: v1alpha1
    kind: AntreaConfig
  patch: |-
    - op: replace
      path: /spec/antreaNSX/enable
      value: true
replacements:
  - path: cluster-ref.yaml