apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../../base/vks-cluster
- ../../../base/cluster-argocd-attach
components:
- ../../../components/ha-control-plane
- ../../../components/antrea-nsx
- ../../../components/argocd-tenant-cluster
- ../../../components/cluster-var-injector


configMapGenerator:
  - name: vars
    literals:
      - cluster_name=dev1-cluster
      - project=tenant1
    options:
      disableNameSuffixHash: true
      annotations:
        config.kubernetes.io/local-config: "true"