apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
components:
- ../../components/stacks/standard
- ../../components/stacks/service-mesh
- ../../components/stacks/observability
- ../../components/envs/dev

